spring:
  application:
    name: gateway
  cloud:
    # loadbalancer:
    #   ribbon:
    #     enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: http://employee
          predicates:
            - Path=/employee/**
            - Method=GET,POST
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department
          uri: http://department
          predicates:
            - Path=/department/**
            - Method=GET,POST
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization
          uri: http://organization
          predicates:
            - Path=/organization/**
            - Method=GET,POST
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
server:
  forward-headers-strategy: framework
springdoc:
  cache:
    disabled: true