spring:
  application:
    name: gateway
  cloud:
    # loadbalancer:
    #   ribbon:
    #     enabled: false
    gateway:
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee
          uri: http://employee
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department
          uri: http://department
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization
          uri: http://organization
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
server:
  forward-headers-strategy: framework
springdoc:
  cache:
    disabled: true