apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{service}}
  namespace: {{namespace}}
  labels:
    app: {{service}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{service}}
  template:
    metadata:
      labels:
        app: {{service}}
    spec:
      containers:
      - name: {{service}}
        image: {{image}}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{service}}
              key: database-name
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{service}}
              key: database-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{service}}
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: {{service}}
  namespace: {{namespace}}
  labels:
    app: {{service}}
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: {{service}}